document.write('<div class="content-nav">'
+'<ul>'
    +'<li><a class="active" ui-sref="">快速开始</a></li>'
    +'<li><a href="./load.html">加载3D场景</a></li>'
    +'<li><a href="">场景对象</a></li>'
    +'<li><a href="">3D与事件</a></li>'
    +'<li><a href="">3D选择器</a></li>'
    +'<li><a href="">3D控件</a></li>'
    +'<li><a href="">面板UI</a></li>'
    +'<li><a href="">3D动画</a></li>'
+'</ul>'
+'</div>')