document.write('<script src="https://speech.uinnova.com/static/lib/ace-builds/src-noconflict/ace.js"></script>\
<script src="https://speech.uinnova.com/static/lib/ace-builds/src-noconflict/ext-language_tools.js"></script>\
<!-- <script src="../lib/ScriptEditor/assets/plugin/ace-builds/src-noconflict/ace.js"></script> -->\
<!-- <script src="../lib/ScriptEditor/assets/plugin/ace-builds/src-noconflict/ext-language_tools.js"></script> -->\
<script src="../lib/ScriptEditor/assets/plugin/jquery/js/jquery-latest.js"></script>\
<script src="../js/sample.js"></script>\
<script src="../lib/ScriptEditor/javascripts/nodejs.js"></script>\
<script src="../lib/ScriptEditor/demos/demos.js"></script>\
<!-- <script src="../lib/ScriptEditor/javascripts/editor.js"></script> -->');